#
# © 2026-present https://github.com/cengiz-pz
#

pluginNodeName=Vision
pluginModuleName=vision
pluginPackage=org.godotengine.plugin.vision
pluginVersion=1.0
godotVersion=4.6
godotReleaseType=stable
gradleProjectName=godot-vision-plugin
#extra.myProperty=value
#gradle.extraGradle=extra.gradle.kts
